# IntelliJ Platform Artifacts Repositories -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html
pluginGroup=com.drinchev.projectlabel
pluginName=Project Label
pluginRepositoryUrl=https://github.com/drinchev/project-label
# SemVer format -> https://semver.org
pluginVersion=1.3.1
# Supported build number ranges and IntelliJ Platform versions -> https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
pluginSinceBuild=241
pluginUntilBuild=
# IntelliJ Platform Properties -> https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#configuration-intellij-extension
platformType=IC
platformVersion=2024.1.7
# Gradle Releases -> https://github.com/gradle/gradle/releases
gradleVersion=8.13